blank_issues_enabled: true
contact_links:
  - name: Security report
    url: https://github.com/yassinbahri/django-index-optimizer/security/advisories/new
    about: Privately report a potential security vulnerability.
